CREATE DATABASE PROYECTO3EVAL;

USE PROYECTO3EVAL;


CREATE TABLE STUDENT(
  id INT AUTO_INCREMENT,
  dni VARCHAR(9) NOT NULL,
  name VARCHAR(100) NOT NULL,
  mail VARCHAR(100) NOT NULL,
  pass VARCHAR(100) NOT NULL,
  image VARCHAR(100) NOT NULL,
  PRIMARY KEY (id));
  
  
CREATE TABLE TEACHER(
  id INT AUTO_INCREMENT,
  dni VARCHAR(9) NOT NULL,
  name VARCHAR(100) NOT NULL,
  mail VARCHAR(100) NOT NULL,
  pass VARCHAR(100) NOT NULL,
  image VARCHAR(100) NOT NULL,
  PRIMARY KEY (id));
  
  
CREATE TABLE SUBJECT(
  id INT AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  hours INT NOT NULL,
  id_teacher INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (id_teacher) REFERENCES TEACHER(id));

CREATE TABLE STUDENTSUBJECT(
	id_subject INT NOT NULL,
    id_student INT NOT NULL,
	FOREIGN KEY (id_subject) REFERENCES SUBJECT (id),
	FOREIGN KEY (id_student) REFERENCES STUDENT (id));

CREATE TABLE ACTIVITY(
	id INT AUTO_INCREMENT,
	description VARCHAR(1000) NOT NULL,
	name VARCHAR(100) NOT NULL,
	percent int NOT NULL,
	media_file VARCHAR(500),
    id_subject INT NOT NULL,
	PRIMARY KEY (id),
    FOREIGN KEY (id_subject) REFERENCES SUBJECT (id));
  
  
CREATE TABLE INSCRIPTION(
	id_student INT NOT NULL,
    id_act INT NOT NULL,
    nota INT NOT NULL,
	FOREIGN KEY (id_act) REFERENCES ACTIVITY (id),
	FOREIGN KEY (id_student) REFERENCES STUDENT (id));